### ISSUE TITLE
Ревью

### ISSUE THREAD

**Issue by talantbekov123** [AndreyZadachin/AndreyZadachin.github.io#1]
Здравствуйте. Благодарю за проделанную работу! К сожалению текущая реализация содержит недостаток, не позволяющий мне засчитать работу на данной итерации.
Похвально что поля номер телефона и почта работают. Проставленны теги. Все корректно открывает на github pages.

**Надо исправить**
- “http://some.test.yandex.ru” не проходят валидацию адреса с поддоменами.
- Проверку проходит следующий некорректный адре сайта http://ya.ru:00000, http://11.11.11.11:0000 (в IPv4 порт это целое число равное максимум 65535, так как это целое число, то несколько нулей подряд являются невалидными). Подробнее про порты можно почитать [тут](https://buy.fineproxy.org/articles/chto-takoe-port-servera.html)
- Не полностью заполнен readme. В оформленном readme.md должна быть проставленная версия, есть заголовок, ссылка на проект работающий на github pages.

**Можно лучше:**
- файлы logo.svg и cover.jpg, расположенные в репозитории не используются на странице (загружаются с серверов Яндекса). Просьба либо задействовать их либо удалить.
- Добавьте .gitignore, содержащий правила, исключающие попадание временных и\или системных файлов в репозиторий.
- В почте может присутствовать точка (Например review.kairat@yandex.ru, review@mail.yandex.ru)

**Comment by AndreyZadachin** [comment]
Здравствуйте.
Спасибо за точные замечания!
Все было исправлено, включая Можно лучше.
Не все было просто конечно))

**Comment by talantbekov123** [comment]
Отличная работа! Все исправлено!

**Похвально**
- эфективное регулярное выражение
- оформленное readme.md
- работа на github pages, все поля работают
- нет лишних файлов в репозитории
- требования к веткам соблюдены
- в поле url реализованы все проверки (ip, dns, http/s)
